/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor.project;

/**
 *
 * @author robinthomas
 */
public class registrationpage extends javax.swing.JFrame {

    /**
     * Creates new form registrationpage
     */
    public registrationpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        vpass = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        fnames = new javax.swing.JTextField();
        lnames = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        emailid = new javax.swing.JTextField();
        maleradio = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        femaleradio = new javax.swing.JRadioButton();
        dobchoose = new com.toedter.calendar.JDateChooser();
        vpassword = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRATION");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 29, 298, -1));

        fname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fname.setText("First Name");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 201, 85, 24));

        lname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lname.setText("Last Name");
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 246, -1, -1));

        gender.setBackground(new java.awt.Color(51, 255, 255));
        gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 281, -1, -1));

        dob.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dob.setText("D.O.B");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 319, -1, -1));

        contact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        contact.setText("Contact NO.");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 350, -1, -1));

        pass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pass.setText("Password");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 412, -1, -1));

        vpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vpass.setText("Verify Password");
        getContentPane().add(vpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 443, -1, -1));

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        email.setText("Email-ID");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 381, -1, -1));

        submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 483, -1, -1));
        getContentPane().add(fnames, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 204, 144, -1));
        getContentPane().add(lnames, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 243, 144, -1));
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 347, 144, -1));
        getContentPane().add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 378, 144, -1));

        maleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradioActionPerformed(evt);
            }
        });
        getContentPane().add(maleradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 274, -1, -1));

        jLabel10.setText("Male");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 281, -1, -1));

        jLabel11.setText("Female");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 281, -1, -1));

        femaleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradioActionPerformed(evt);
            }
        });
        getContentPane().add(femaleradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 274, -1, -1));
        getContentPane().add(dobchoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 316, 143, -1));
        getContentPane().add(vpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 144, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 409, 144, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 29, 61, 42));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Reg No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 166, 66, -1));
        getContentPane().add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 163, 144, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleradioActionPerformed

    private void femaleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleradioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField con;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dob;
    private com.toedter.calendar.JDateChooser dobchoose;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailid;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField fnames;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField lnames;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField password;
    private javax.swing.JButton submit;
    private javax.swing.JTextField uid;
    private javax.swing.JLabel vpass;
    private javax.swing.JTextField vpassword;
    // End of variables declaration//GEN-END:variables
}
